"""Controlled Windows OS Automation & Computer Interaction Layer for JARVIS (Phase 08)."""

from jarvis.os.config import OSAutomationConfig
from jarvis.os.errors import (
    ClipboardAccessError,
    CoordinatesOutOfBoundsError,
    DirectExecutionDeniedError,
    DisplayCaptureError,
    InputDispatchError,
    KeyNotAllowedError,
    OSAutomationError,
    OSNotSupportedError,
    OSPermissionDeniedError,
    OSSecurityError,
    OSVerificationError,
    ResourceExhaustionError,
    WindowAmbiguityError,
    WindowNotFoundError,
    WindowOperationError,
)
from jarvis.os.manager import OSAutomationManager
from jarvis.os.models import (
    ClipboardClearRequest,
    ClipboardData,
    ClipboardFormat,
    ClipboardReadRequest,
    ClipboardWriteRequest,
    CoordinateSpace,
    DisplayInfo,
    InputModifier,
    KeyboardHotkeyRequest,
    KeyboardKeyRequest,
    KeyboardTypeRequest,
    MonitorInfo,
    MouseButton,
    MouseClickRequest,
    MouseMoveRequest,
    MouseScrollRequest,
    OSActionResult,
    Point2D,
    Rect2D,
    ScreenCaptureRequest,
    ScreenCaptureResult,
    SystemInfoResult,
    VerificationMethod,
    VerificationRequest,
    VerificationResult,
    WindowAction,
    WindowActionRequest,
    WindowInfo,
    WindowQuery,
    WindowState,
)
from jarvis.os.providers.base import OSProvider
from jarvis.os.providers.mock import MockOSProvider
from jarvis.os.providers.windows import WindowsOSProvider
from jarvis.os.security import OSSecurityManager
from jarvis.os.tools.registration import ALL_OS_TOOLS, register_os_tools

__all__ = [
    # Config & Manager
    "OSAutomationConfig",
    "OSAutomationManager",
    "OSSecurityManager",
    # Providers
    "OSProvider",
    "WindowsOSProvider",
    "MockOSProvider",
    # Models
    "Point2D",
    "Rect2D",
    "CoordinateSpace",
    "MouseButton",
    "InputModifier",
    "WindowState",
    "WindowAction",
    "MonitorInfo",
    "DisplayInfo",
    "WindowInfo",
    "WindowQuery",
    "WindowActionRequest",
    "ScreenCaptureRequest",
    "ScreenCaptureResult",
    "MouseMoveRequest",
    "MouseClickRequest",
    "MouseScrollRequest",
    "KeyboardTypeRequest",
    "KeyboardKeyRequest",
    "KeyboardHotkeyRequest",
    "ClipboardFormat",
    "ClipboardData",
    "ClipboardReadRequest",
    "ClipboardWriteRequest",
    "ClipboardClearRequest",
    "SystemInfoResult",
    "VerificationMethod",
    "VerificationRequest",
    "VerificationResult",
    "OSActionResult",
    # Errors
    "OSAutomationError",
    "OSSecurityError",
    "DirectExecutionDeniedError",
    "CoordinatesOutOfBoundsError",
    "KeyNotAllowedError",
    "ResourceExhaustionError",
    "OSNotSupportedError",
    "OSPermissionDeniedError",
    "WindowNotFoundError",
    "WindowAmbiguityError",
    "WindowOperationError",
    "DisplayCaptureError",
    "InputDispatchError",
    "ClipboardAccessError",
    "OSVerificationError",
    # Tools
    "ALL_OS_TOOLS",
    "register_os_tools",
]
